config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  get '/destroy_all', to: 'users#destroy_all'
  get '/get_scores', to: 'users#get_scores'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'net/http'
  require 'uri'
  def index
    @users = User.all
  end

  def get_scores
    begin
      User.delete_all
      uri = URI.parse("https://www.lpga.com/tournaments/volvik-founders-cup/results?filters=2019&archive=")
      response = Net::HTTP.get_response(uri)
      @status = create_records(Nokogiri::HTML.parse(response.body))
      @users = User.all
    rescue Exception => e
    end
  end

  def create_records(parse_data)
    begin
      parse_data.search('.player-dropdown-wrapper').each_with_index do |data,index|
        name = data.search('.player-name').first.content
        scores = parse_data.search('.scores')[index].content.gsub(/\s/,'')
        static_url = data.search('.player-data-container')[0].values[1]
        res = Net::HTTP.get_response(URI.parse("https://www.lpga.com#{static_url}"))
        parse_data1 = Nokogiri::HTML.parse(res.body)
        par = parse_data1.search('.body')[0].content.squish!
        round = parse_data1.search('.body')[1].content.squish!
        status = parse_data1.search('.body')[2].content.squish!
        User.create!(name: name, scores: scores, par: par, round: round, status: status)
      end
      return true
    rescue Exception => e
      return false
    end
  end

  def destroy_all
    User.delete_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def users_count
    if User.count > 0
      return true
    else
      return false
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HondaLpga</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_index.html.erb
<%= link_to 'Delete all records', destroy_all_path, remote: true if users_count %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="center">Name</th>
      <th class="center" width="100px">Scores</th>
      <th colspan="22" class="center">Full Scorecard</th>
    </tr>
  </thead>
  <tbody>
    <% if user_flag %>
      <% @users.each do |user| %>
        <tr>
         <td rowspan="4" class="name_style"><%= user.name %></td>
        <td rowspan="4" class="name_style"><%= user.scores %></td>
         <td class="cell_bold">Hole</td>
         <td class="cell_bold">1</td>
         <td class="cell_bold">2</td>
         <td class="cell_bold">3</td>
         <td class="cell_bold">4</td>
         <td class="cell_bold">5</td>
         <td class="cell_bold">6</td>
         <td class="cell_bold">7</td>
         <td class="cell_bold">8</td>
         <td class="cell_bold">9</td>
         <td class="cell_bold">Out</td>
         <td class="cell_bold">10</td>
         <td class="cell_bold">11</td>
         <td class="cell_bold">12</td>
         <td class="cell_bold">13</td>
         <td class="cell_bold">14</td>
         <td class="cell_bold">15</td>
         <td class="cell_bold">16</td>
         <td class="cell_bold">17</td>
         <td class="cell_bold">18</td>
         <td class="cell_bold">In</td>
         <td class="cell_bold">Tot</td>
       </tr>
        <tr>
          <% user.par.gsub(/\s+/m, ' ').strip.split(" ").each do |a| %>
            <td> <%= a %></td>
          <% end %>
        </tr>
        <tr>
          <% user.round.gsub(/\s+/m, ' ').strip.split(" ").each do |a| %>
            <td><%= a %></td>
          <% end %>
        </tr>
        <tr>
          <% user.status.gsub(/\s+/m, ' ').strip.split(" ").each do |a| %>
            <td><%= a %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
  <%= link_to 'Get player scores', get_scores_path , remote: true if !users_count %>
</div>

app/views/users/destroy_all.js.erb
$("#common_page").html("<%= escape_javascript render(:partial => 'index', :locals => {:user_flag => false}) %>");

app/views/users/get_scores.js.erb
<% if @status %>
  $("#common_page").html("<%= escape_javascript render(:partial => 'index', :locals => {:user_flag => true}) %>");
<% else %>
  alert('Something went wrong. Please try after sometime.')
<% end %>

app/views/users/index.html.erb
<div class="container" id="common_page">
  <%= render :partial => 'index', :locals => {:user_flag => true} %>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    myFunction();
    function myFunction() {
      setInterval(function(){ get_data_api(); },900000);
    }
  });
</script>